background {
    color = rgba(050505ff)
}

input-field {
    size = 300, 50
    position = 0, -80

    dots_center = true
    fade_on_empty = false

    outline_thickness = 2

    font_color = rgb(50fa7b)
    inner_color = rgb(101010)
    outer_color = rgb(00ff66)

    check_color = rgb(50fa7b)
    fail_color = rgb(ff5555)
}

label {
    text = cmd[update:1000] echo "$(date +"%H:%M")"
    font_size = 72
    position = 0, 120
    color = rgb(50fa7b)
}

label {
    text = I Have Control Of You
    font_size = 15
    position = 0, 40
    color = rgb(3fb950)
}
